### PR TITLE
Emacs org roam m1 with setup

### PR DESCRIPTION
**Pull request by esquivalient**
There's a description of Org Roam in the files. I'm using it as part of my organization system. It is awesome.

### CODE REVIEW

**Comment by mediocretes** [comment]
I get these errors on startup:

```
Error (use-package): Failed to install exec-path-from-shell: Package ‘exec-path-from-shell-’ is unavailable
Error (use-package): exec-path-from-shell/:init: Symbol’s function definition is void: exec-path-from-shell-initialize
Error (use-package): Cannot load exec-path-from-shell
Warning (initialization): An error occurred while loading ‘/Users/nathan/.emacs.d/init.el’:

File is missing: Creating directory, No such file or directory, /Users/nathan/Dropbox/OrgRoam
```

Unrelated, maybe the tmp.org should be called something other than tmp, if it's intended to be a quick brain dump file? idk, that's less important than the startup issue.

**Comment by esquivalient** [comment]
I only remember you have a problem here when I have no access to you. It seems like it failed to fetch from MELPA, but it's definitely still in MELPA. Any chance it was an intermittent failure?

**Review by mediocretes — CHANGES_REQUESTED** [review]
I have the same error as before, but this did drive me to update emacs, but I have the same error as before. Let's look at it together sometime.

**Comment by mediocretes** [comment]
We debugged this in person. Short version, I had a weird/bad symlink in my elpa/gnu/ directory. We deleted it and let emacs start from scratch. Also, I had split my dropbox into two directories, neither named "~/Dropbox", so we added a symlink with that name to make the dropbox parts of Org Roam work.

**Review by mediocretes — APPROVED** [review]

**Pull request merged**
